
DESTDIR=/home/len/repos/lenjaffe.com/AdventPlanet

all: main_html
main_html: $(DESTDIR)/index.html.gz $(DESTDIR)/news.html.gz $(YEARS)

# regenerate gzipped assets
$(DESTDIR)/index.html.gz: $(DESTDIR)/index.html
	(cd $(DESTDIR); git checkout development; gzip -c index.html > index.html.gz; git add index.html.gz)


$(DESTDIR)/news.html.gz: $(DESTDIR)/news.html
	(cd $(DESTDIR); git checkout development; gzip -c news.html > news.html.gz; git add news.html.gz)




