title: 2011-12-02
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

RJBS Hanukkah 2011: is available from L<12/21|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-21.html>-L<12/28|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-28.html>

L<Perl:  Perl Advent Calendar 2011 -  Keeping up with the Joneses  |http://perladvent.org/2011/2011-12-02.html>

L<Catalyst: Catalyst Advent Calendar - Day 2|http://www.catalystframework.org/calendar/2011/2>

L<Dancer:  Simple CRUD with Dancer::Plugin::SimpleCRUD - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/2>

L<Perl 6: 2011  December  02 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/2/>

=head2 Perl Advent Calendar Japan:

L<acme: Acme::PrettyCure - プリキュアは永遠に不滅です - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/2>

L<casual: Encode::Locale - 環境に合わせたエンコーディングを提供する - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/2>

L<teng: #02 schemaの定義方法 - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/2>

L<dbix: オレオレDBIxへの第一歩 - DBIのサブクラスを作る - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/2>

L<anysan: the difference between AnyEvent::IRC::Client - Perl Advent Calendar Japan 2011 Anysan Track|http://perl-users.jp/articles/advent-calendar/2011/anysan/2>

L<hacker: Alien::RRDtool - RRDtoolをCPANから入れる - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/2>

L<test: use Test::Attribute::AutoLevel - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/2>

L<amon2: どの Flavor つかったらいいのん? - Perl Advent Calendar Japan 2011 Amon2 Track|http://perl-users.jp/articles/advent-calendar/2011/amon2/2>

L<english: There&apos;s more than one Perl Mongers in Japan - Perl Advent Calendar Japan 2011 English Track|http://perl-users.jp/articles/advent-calendar/2011/english/2>

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

