title: 2011-12-18
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl:  Perl Advent Calendar 2011 -  Munge All the Filenames!  |http://perladvent.org/2011/2011-12-18.html>

L<Catalyst: Catalyst Advent Calendar - Day 18|http://www.catalystframework.org/calendar/2011/18>

L<Dancer:  Alternative Dancer Templating Engines - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/18>

L<Perl 6: 2011  December  18 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/18/>

=head2 Perl Advent Calendar Japan:

L<acme: SQL::MakerのAcme的利用について - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/18>

L<casual: Net::eBayで自分が好きなアーティスト作品の出品情報を常時取得する - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/18>

L<teng: #18 Plugin - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/18>

L<dbix: ビットを使って複雑な条件を簡単にする - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/18>

anysan: unavailable

hacker: unavailable

L<test: テストのためにデーモンを自動的に起動するやりかた2011年版 - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/18>

amon2: unavailable

english: unavailable

=head1 Python

L<Ball Pythons: December 18 - Advent calendar - World of Ball Pythons|http://www.worldofballpythons.com/christmas/18/>

