title: 2011-12-10
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl:  Perl Advent Calendar 2011 -  A Big List of Stuff You Want  |http://perladvent.org/2011/2011-12-10.html>

L<Catalyst: Catalyst Advent Calendar - Day 10|http://www.catalystframework.org/calendar/2011/10>

L<Dancer:  Portable file handling in Dancer apps - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/10>

L<Perl 6: 2011  December  10 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/10/>

=head2 Perl Advent Calendar Japan:

L<acme: Acme::DragonBall - つっかもうぜ！ドラ○ンボール！ - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/10>

L<casual: Object::Container ‐ Containerを使って開発スピードをあげる - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/10>

L<teng: #10 Rowクラスの拡張方法 - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/10>

L<dbix: 生DBIの構成例 - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/10>

anysan: unavailable

L<hacker: FarmBalance: Webファームシステムにおけるデータ件数やトランザクション量等の均等分散 - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/10>

L<test: Perlテストのリファクタリング的なあれ - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/10>

amon2: unavailable

english: unavailable

=head1 Python

L<Ball Pythons: December 10 - Advent calendar - World of Ball Pythons|http://www.worldofballpythons.com/christmas/10/>

