title: 2011-12-24
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl:  Perl Advent Calendar 2011 -  Where Does He Get Those Wonderful Codepoints?  |http://perladvent.org/2011/2011-12-24.html>

L<Catalyst: Catalyst Advent Calendar - Day 24|http://www.catalystframework.org/calendar/2011/24>

L<Dancer:  Thanking the contributors - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/24>

L<Perl 6: 2011  December  24 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/24/>

=head2 Perl Advent Calendar Japan:

L<acme: 聖夜に暖炉の前でする話 - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/24>

L<casual: Data::Section::Simpleで__DATA__をカジュアルに使おう！ - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/24>

teng: unavailable

L<dbix: DBIC/Skinnyユーザ向けにDBIx::Skinny::Cookbookを書いてみた - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/24>

anysan: unavailable

L<hacker: BokkaKumiai: 音楽のコード進行解析とギタータブ譜出力 - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/24>

L<test: テストダブルについて - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/24>

amon2: unavailable

english: unavailable

=head1 Python

L<Ball Pythons: December 24 - Advent calendar - World of Ball Pythons|http://www.worldofballpythons.com/christmas/24/>

