title: 2011-12-10
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

RJBS Hanukkah 2011: is available from L<12/21|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-21.html>-L<12/28|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-28.html>

L<Perl:  Perl Advent Calendar 2011 -  A Big List of Stuff You Want  |http://perladvent.org/2011/2011-12-10.html>

L<Catalyst: Catalyst Advent Calendar - Day 10|http://www.catalystframework.org/calendar/2011/10>

L<Dancer:  Portable file handling in Dancer apps - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/10>

L<Perl 6: 2011  December  10 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/10/>

=head2 Perl Advent Calendar Japan:

L<acme: Acme::DragonBall - つっかもうぜ！ドラ○ンボール！ - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/10>

L<casual: Object::Container ‐ Containerを使って開発スピードをあげる - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/10>

L<teng: #10 Rowクラスの拡張方法 - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/10>

L<dbix: 生DBIの構成例 - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/10>

anysan: is unavailable.

L<hacker: FarmBalance: Webファームシステムにおけるデータ件数やトランザクション量等の均等分散 - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/10>

L<test: Perlテストのリファクタリング的なあれ - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/10>

amon2: is unavailable.

english: is unavailable.

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

