title: 2011-12-12
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl:  Perl Advent Calendar 2011 -  Now I have an SQL machine gun  |http://perladvent.org/2011/2011-12-12.html>

L<Catalyst: Catalyst Advent Calendar - Day 31|http://www.catalystframework.org/calendar/2011/12>

L<Dancer:  Dancer workshop at London Perl Workshop 2011 - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/12>

L<Perl 6: 2011  December  12 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/12/>

=head2 Perl Advent Calendar Japan:

L<acme: 子　　　　　（Acme::Time::Baby） - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/12>

L<casual: カジュアルにperlデバッガを使って捗る - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/12>

L<teng: #12 schema loader - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/12>

L<dbix: オレオレDBIxでMySQLやOracleの実行計画を一瞬にして採る（採りたい）！ - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/12>

anysan: unavailable

L<hacker: Time::Piece::Plus - Time::Pieceに便利メソッドを - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/12>

L<test: bless を使った Casual な Test Double について - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/12>

amon2: unavailable

english: unavailable

=head1 Python

L<Ball Pythons: December 12 - Advent calendar - World of Ball Pythons|http://www.worldofballpythons.com/christmas/12/>

