title: 2011-12-13
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl:  Perl Advent Calendar 2011 -  The new /r flag  |http://perladvent.org/2011/2011-12-13.html>

L<Catalyst: Catalyst Advent Calendar - Day 31|http://www.catalystframework.org/calendar/2011/13>

L<Dancer:  Serving Files with Dancer::Plugin::DirectoryView and Dancer::Plugin::Auth::Htpasswd - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/13>

L<Perl 6: 2011  December  13 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/13/>

=head2 Perl Advent Calendar Japan:

L<acme: の　　　　　（Acme::No） - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/13>

L<casual: Net::Google::Analyticsを使ってGoogle Analyticsのデータを引っ張る - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/13>

L<teng: #13 schema meta data api - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/13>

L<dbix: DBI::Profileでお手軽プロファイリング - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/13>

anysan: unavailable

L<hacker: Skype::AnyでSkype botを作る - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/13>

L<test: perl ♡ tests - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/13>

amon2: unavailable

english: unavailable

=head1 Python

L<Ball Pythons: December 13 - Advent calendar - World of Ball Pythons|http://www.worldofballpythons.com/christmas/13/>

