title: 2011-12-17
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl:  Perl Advent Calendar 2011 -  There is No Try  |http://perladvent.org/2011/2011-12-17.html>

L<Catalyst: Catalyst Advent Calendar - Day 17|http://www.catalystframework.org/calendar/2011/17>

L<Dancer:  Dancer plugins ecosystem - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/17>

L<Perl 6: 2011  December  17 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/17/>

=head2 Perl Advent Calendar Japan:

L<acme: Acmeモジュールで捗るはなし - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/17>

L<casual: Term::UI - サクッと対話的に入力を求める - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/17>

L<teng: #17 error handling - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/17>

L<dbix: DBIx::Class で FORCE INDEX する方法 - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/17>

anysan: unavailable

L<hacker: FormValidator::Simple::Plugin::V8 - バリデーションルールをサーバー/クライアントで共有するためのモジュール - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/17>

L<test: ちょっと他言語に行ったら例えば RSpec にハマった人のために - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/17>

amon2: unavailable

english: unavailable

=head1 Python

L<Ball Pythons: December 17 - Advent calendar - World of Ball Pythons|http://www.worldofballpythons.com/christmas/17/>

