title: 2011-12-21
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<RJBS Hanukkah 2011:  RJBS Hanukkah Calendar 2011 -  It&#39;s Just a Palette Swap  |http://xn--8dbbfrx.rjbs.manxome.org/2011/2011-12-21.html>

L<Perl:  Perl Advent Calendar 2011 -  A Shortcut to Unicode  |http://perladvent.org/2011/2011-12-21.html>

L<Catalyst: Catalyst Advent Calendar - Day 31|http://www.catalystframework.org/calendar/2011/21>

L<Dancer:  Making RSS feeds using Dancer::Plugin::Feed - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/21>

L<Perl 6: 2011  December  21 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/21/>

=head2 Perl Advent Calendar Japan:

L<acme: Acme何thing?　番外編 - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/21>

L<casual: Getopt::Longでコマンドラインのオプション指定をサクっと簡単に取得する - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/21>

teng: is unavailable.

L<dbix: SQL::Interpで生がお好きなあなたも満足 - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/21>

anysan: is unavailable.

L<hacker: Perl::Metrics::Lite - プラガブルなメトリクス測定モジュール - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/21>

L<test: prove についてのおさらい - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/21>

amon2: is unavailable.

english: is unavailable.

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

