title: 2011-12-08
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

RJBS Hanukkah 2011: is available from L<12/21|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-21.html>-L<12/28|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-28.html>

L<Perl:  Perl Advent Calendar 2011 -  All the perls are all lined up  |http://perladvent.org/2011/2011-12-08.html>

L<Catalyst: Catalyst Advent Calendar - Day 31|http://www.catalystframework.org/calendar/2011/8>

L<Dancer:  Dancer 2, or Why I Rewrote Everything - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/8>

L<Perl 6: 2011  December  08 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/8/>

=head2 Perl Advent Calendar Japan:

L<acme: Acme::Time::Reverse - 時間を戻したい貴方のために - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/8>

L<casual: Plack::Middlewareの使い所 - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/8>

L<teng: #08 search - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/8>

L<dbix: DBIx::Simple ふたたび - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/8>

anysan: is unavailable.

L<hacker: App::pfswatch - ファイルの変更を検知して、指定したコマンドを実行する - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/8>

L<test: HTTP通信を含むモジュールのテスト - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/8>

amon2: is unavailable.

english: is unavailable.

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

