title: 2011-12-22
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<RJBS Hanukkah 2011:  RJBS Hanukkah Calendar 2011 -  It&#39;s Only a Model!  |http://xn--8dbbfrx.rjbs.manxome.org/2011/2011-12-22.html>

L<Perl:  Perl Advent Calendar 2011 -  Less Tedium, More Transactions  |http://perladvent.org/2011/2011-12-22.html>

L<Catalyst: Catalyst Advent Calendar - Day 22|http://www.catalystframework.org/calendar/2011/22>

L<Dancer:  Generating CAPTCHAs using Dancer::Plugin::Captcha::SecurityImage - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/22>

L<Perl 6: 2011  December  22 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/22/>

=head2 Perl Advent Calendar Japan:

L<acme: お米モジュールの衝撃と木目モジュールの慟哭 - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/22>

L<casual: Webスクレイピング入門 - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/22>

teng: is unavailable.

L<dbix: 敢えてDBIx::Connectorを紹介してやろうじゃないか - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/22>

anysan: is unavailable.

L<hacker: STF分散オブジェクトストレージ - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/22>

L<test: CPAN::Mini::DevelとCPAN::Reporter::Smokerで簡単スモーキング - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/22>

amon2: is unavailable.

english: is unavailable.

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

