title: 2011-12-20
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

RJBS Hanukkah 2011: is available from L<12/21|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-21.html>-L<12/28|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-28.html>

L<Perl:  Perl Advent Calendar 2011 -  Revisiting Test::Routine  |http://perladvent.org/2011/2011-12-20.html>

L<Catalyst: Catalyst Advent Calendar - Day 31|http://www.catalystframework.org/calendar/2011/20>

L<Dancer:  High-performance Dancer apps - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/20>

L<Perl 6: 2011  December  20 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/20/>

=head2 Perl Advent Calendar Japan:

L<acme: Acme何thing?　解答編 - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/20>

L<casual: Calendar::Japanese::Holiday - 日本の祝日を求める - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/20>

L<teng: #20 標準Plugin2 - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/20>

L<dbix: DBIx::QueryLog でクエリの実行計画も丸見えにする！ - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/20>

anysan: is unavailable.

hacker: is unavailable.

L<test: Devel::CoverとJenkins - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/20>

amon2: is unavailable.

english: is unavailable.

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

