title: 2011-12-11
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

RJBS Hanukkah 2011: is available from L<12/21|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-21.html>-L<12/28|http://lenjaffe.com/PerlAdventPlanet/2011/2011-12-28.html>

L<Perl:  Perl Advent Calendar 2011 -  Mojolicious as a client  |http://perladvent.org/2011/2011-12-11.html>

L<Catalyst: Catalyst Advent Calendar - Day 11|http://www.catalystframework.org/calendar/2011/11>

L<Dancer:  Dancer 2, a Roadmap - PerlDancer Advent Calendar|http://advent.perldancer.org/2011/11>

L<Perl 6: 2011  December  11 -- Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2011/12/11/>

=head2 Perl Advent Calendar Japan:

L<acme: 餃　　　　　（Acme::Chef） - Perl Advent Calendar Japan 2011 Acme Track|http://perl-users.jp/articles/advent-calendar/2011/acme/11>

L<casual: Mojolicious::Liteでウェブツールを作ろう - Perl Advent Calendar Japan 2011 Casual Track|http://perl-users.jp/articles/advent-calendar/2011/casual/11>

L<teng: #11 inflate / deflate - Perl Advent Calendar Japan 2011 Teng Track|http://perl-users.jp/articles/advent-calendar/2011/teng/11>

L<dbix: DBI のお供になりそうなモジュールたち - Perl Advent Calendar Japan 2011 Dbix Track|http://perl-users.jp/articles/advent-calendar/2011/dbix/11>

anysan: is unavailable.

L<hacker: データ分散とインデックス最適化のためのハッシュ関数の利用 - Perl Advent Calendar Japan 2011 Hacker Track|http://perl-users.jp/articles/advent-calendar/2011/hacker/11>

L<test: Jenkinsで継続的メトリクス測定のすすめ - Perl Advent Calendar Japan 2011 Test Track|http://perl-users.jp/articles/advent-calendar/2011/test/11>

amon2: is unavailable.

english: is unavailable.

=head1 Python

Ball Pythons: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by daqy of month llike everybody else.
You can find the PHP Advent Calendar at L<PHP Advent|http://phpadvent.org/2011>

=head1 SysAdvent
 
Advent Calendar for System Administrators - uses slugs, not numbers - find the home page at L<SysAdvent|http://sysadvent.blogspot.com>

