title: 2011-12-12
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-12.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/12>

L<Dancer|http://advent.perldancer.org/2011/12>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/12/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/12>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/12>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/12>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/12>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/12>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/12>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/12>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/12>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/12>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/12/>

