title: 2011-12-20
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-20.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/20>

L<Dancer|http://advent.perldancer.org/2011/20>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/20/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/20>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/20>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/20>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/20>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/20>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/20>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/20>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/20>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/20>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/20/>

