title: 2011-12-19
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-19.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/19>

L<Dancer|http://advent.perldancer.org/2011/19>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/19/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/19>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/19>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/19>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/19>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/19>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/19>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/19>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/19>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/19>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/19/>

