title: 2011-12-21
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-21.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/21>

L<Dancer|http://advent.perldancer.org/2011/21>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/21/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/21>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/21>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/21>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/21>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/21>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/21>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/21>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/21>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/21>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/21/>

