title: 2011-12-13
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-13.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/13>

L<Dancer|http://advent.perldancer.org/2011/13>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/13/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/13>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/13>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/13>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/13>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/13>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/13>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/13>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/13>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/13>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/13/>

