title: 2011-12-17
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-17.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/17>

L<Dancer|http://advent.perldancer.org/2011/17>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/17/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/17>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/17>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/17>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/17>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/17>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/17>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/17>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/17>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/17>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/17/>

