title: 2011-12-06
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-06.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/6>

L<Dancer|http://advent.perldancer.org/2011/6>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/6/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/6>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/6>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/6>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/6>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/6>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/6>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/6>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/6>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/6>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/6/>

