title: 2011-12-09
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-09.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/9>

L<Dancer|http://advent.perldancer.org/2011/9>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/9/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/9>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/9>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/9>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/9>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/9>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/9>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/9>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/9>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/9>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/9/>

