title: 2011-12-01
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl|http://perladvent.org/2011/2011-12-01.html>

L<Catalyst|http://www.catalystframework.org/calendar/2011/1>

L<Dancer|http://advent.perldancer.org/2011/1>

L<Perl 6|http://perl6advent.wordpress.com/2011/12/1/>

=head2 Perl Advent Calendar Japan:

L<acme|http://perl-users.jp/articles/advent-calendar/2011/acme/1>

L<casual|http://perl-users.jp/articles/advent-calendar/2011/casual/1>

L<teng|http://perl-users.jp/articles/advent-calendar/2011/teng/1>

L<dbix|http://perl-users.jp/articles/advent-calendar/2011/dbix/1>

L<anysan|http://perl-users.jp/articles/advent-calendar/2011/anysan/1>

L<hacker|http://perl-users.jp/articles/advent-calendar/2011/hacker/1>

L<test|http://perl-users.jp/articles/advent-calendar/2011/test/1>

L<amon2|http://perl-users.jp/articles/advent-calendar/2011/amon2/1>

L<english|http://perl-users.jp/articles/advent-calendar/2011/english/1>

=head1 Python

L<Ball Pythons|http://www.worldofballpythons.com/christmas/1/>

