title: 2010-12-03
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: Seasonal Help|http://perladvent.org/2010/3/>

L<Catalyst: Catalyst Advent Calendar - Day 3|http://www.catalystframework.org/calendar/2010/3>

L<Dancer:  Tutorial: writing a tiny blog engine - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/3>

L<Perl 6: 2010  December  03 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/3/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Exceptionally Extensible Exceptions  |http://advent.rjbs.manxome.org/2010/2010-12-03.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: どんなメソッドがあるのかわからない！ - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/3>

L<Symbolic Programming: 記号だけのJavaScriptプログラミングの基本原理 - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/3>

L<Meta Advent Calendar: なにはなくとも12月のカレンダーを出す - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/3>

L<Win32: cmd.exe の C は…… - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/3>

L<Acme: Acme::JavaTrace - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/3>

L<English: Pseudo closures in XS - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/3>

L<Casual: コマンドラインで使えるかもしれないツール等あれこれ - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/3>

L<Hacker: Scope::Container でリソース管理を行う - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/3>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

