title: 2010-12-19
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: So, umm, I told Santa what I wanted and he was totally, like, whatever&hellip;|http://perladvent.org/2010/19/>

L<Catalyst: Catalyst Advent Calendar - Day 19|http://www.catalystframework.org/calendar/2010/19>

L<Dancer:  Writing a new Dancer serializer backend - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/19>

L<Perl 6: 2010  December  19 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/19/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Exporting Globs for Fun and Profit  |http://advent.rjbs.manxome.org/2010/2010-12-19.html>

=head2 Perl Advent Calendar Japan:

L<Perl6:  - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/19>

L<Symbolic Programming: 1分でわかる記号だけのErlangプログラミング - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/19>

L<Meta Advent Calendar:  - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/19>

L<Win32: WindowsでPerlをビルドする - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/19>

L<Acme: AcmeなるモジュールをCPANに求めて - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/19>

L<English: cpan-outdated - detect outdated CPAN modules in your environment - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/19>

L<Casual: WWW::SalesforceでChatterのタイムラインを取得する - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/19>

L<Hacker: ひらがなをカタカナに変換したいだって?それなら Lingua::JA::Regular::Unicode - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/19>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

