title: 2010-12-05
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: Merry Christmap|http://perladvent.org/2010/5/>

L<Catalyst: Catalyst Advent Calendar|http://www.catalystframework.org/calendar/2010/5>

L<Dancer:  How to write a plugin - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/5>

L<Perl 6: 2010  December  05 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/5/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  It&#39;s a Time for Tolerance  |http://advent.rjbs.manxome.org/2010/2010-12-05.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: モジュールを書いてみよう - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/5>

L<Symbolic Programming: 記号だけのPerlプログラミングの基本原理 - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/5>

L<Meta Advent Calendar: Text::Xatena - はてな記法のような記法フォーマットパーサー - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/5>

L<Win32: オススメしないperlの実行方法 - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/5>

L<Acme: Acme::Code::Police vs Acme::Code::FreedomFighter - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/5>

L<English: Furl - Lightning fast HTTP client library - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/5>

L<Casual: Vim と Perl で音楽プレーヤを作ろう - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/5>

L<Hacker: DBIx::Inspector で DB の中をのぞきみる - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/5>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

