title: 2010-12-24
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: 'Twas the night before diffmas|http://perladvent.org/2010/24/>

L<Catalyst: Catalyst Advent Calendar - Day 24|http://www.catalystframework.org/calendar/2010/24>

L<Dancer:  How to contribute to Dancer - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/24>

L<Perl 6: 2010  December  24 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/24/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Rolling Your Own Method Dispatch  |http://advent.rjbs.manxome.org/2010/2010-12-24.html>

=head2 Perl Advent Calendar Japan:

L<Perl6:  - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/24>

L<Symbolic Programming: 6種類の記号だけでJavaScriptを書こう - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/24>

L<Meta Advent Calendar:  - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/24>

L<Win32: Win32::Jobでジョブ管理 - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/24>

L<Acme: dan.pm に迫る - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/24>

L<English: Encode::UTF8Mac makes you happy while handling file names on MacOSX. - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/24>

L<Casual: Smart::Args でバリデーションする。またはバリデーターとして必要な事 - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/24>

L<Hacker: Devel::KYTProfで空気読んだプロファイリングする - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/24>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

