title: 2010-12-07
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: |http://perladvent.org/2010/7/>

L<Catalyst: Catalyst Advent Calendar - Day 7|http://www.catalystframework.org/calendar/2010/7>

L<Dancer:  Storing sessions in cookies - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/7>

L<Perl 6: 2010  December  07 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/7/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Safe, Simple, Deadly  |http://advent.rjbs.manxome.org/2010/2010-12-07.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: インタラクティブな実行環境を使おう - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/7>

L<Symbolic Programming: 86バイナリでも記号プログラミング！ - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/7>

L<Meta Advent Calendar: インデックスに記事のタイトルを出してみる - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/7>

L<Win32: Windows のイベントログで勤務時間を調べよう - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/7>

L<Acme: Acme::AKB48 - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/7>

L<English: POSIX character classes in regexp - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/7>

L<Casual: アクセスログの解析時のDateTimeによる日付処理 - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/7>

L<Hacker: AnyEvent::APNSでiPhoneのプッシュ通知を実装しよう - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/7>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

