title: 2010-12-15
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: $HOME for the holidays|http://perladvent.org/2010/15/>

L<Catalyst: Catalyst Advent Calendar - Day 15|http://www.catalystframework.org/calendar/2010/15>

L<Dancer:  Tutorial: Shrinkr, an URL shortener - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/15>

L<Perl 6: 2010  December  15 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/15/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Lovingly Mass-Produced HTML  |http://advent.rjbs.manxome.org/2010/2010-12-15.html>

=head2 Perl Advent Calendar Japan:

L<Perl6:  - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/15>

L<Symbolic Programming: 記号だけのJavaScriptプログラミングの原理 その2 - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/15>

L<Meta Advent Calendar:  - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/15>

L<Win32: Eject your optical drives! - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/15>

L<Acme: 時にはお伽の話を - Acme::Rumpelstiltskin - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/15>

L<English: Sub::SingletonBuilder - a tiny module to create singletons - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/15>

L<Casual: Path::Classで簡単ファイル操作 - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/15>

L<Hacker: Perl から Growl をちゃんと使おう - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/15>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

