title: 2010-12-16
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: 'Net stockings are barely servicable gift receptacles|http://perladvent.org/2010/16/>

L<Catalyst: Catalyst Advent Calendar|http://www.catalystframework.org/calendar/2010/16>

L<Dancer:  Use cool stuff to render a graph - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/16>

L<Perl 6: 2010  December  16 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/16/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Dealing with an Oversized Interface  |http://advent.rjbs.manxome.org/2010/2010-12-16.html>

=head2 Perl Advent Calendar Japan:

L<Perl6:  - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/16>

L<Symbolic Programming: はじめての80386記号プログラミング - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/16>

L<Meta Advent Calendar:  - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/16>

L<Win32: スライドの下準備にWin32::PowerPointを使う - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/16>

L<Acme: Acme合体で猫-トースト装置をつくる - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/16>

L<English: Net::DNS::Lite - a module for handling timeout of hostname lookups safely, and more - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/16>

L<Casual: HTML::Shakanでフォーム生成・バリデーションからモデル作成まで - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/16>

L<Hacker: Email::MIME::MobileJPで文字コードまわりに気をつかわないでメールの送受信をおこなう - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/16>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

