title: 2010-12-10
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: Catsup Redirect|http://perladvent.org/2010/10/>

L<Catalyst: Catalyst Advent Calendar - Day 10|http://www.catalystframework.org/calendar/2010/10>

L<Dancer:  Deploying Dancer in CGI and VPS Environments - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/10>

L<Perl 6: 2010  December  10 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/10/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  In Lieu of Coal, Naughty Children May Be Given M4 Files  |http://advent.rjbs.manxome.org/2010/2010-12-10.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: echoサーバーを書こう - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/10>

L<Symbolic Programming: C#(ASP.NET 4)で記号プログラミングをやってみたい! - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/10>

L<Meta Advent Calendar: Acvent Calendar Applicationを高速化する - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/10>

L<Win32: それ多分Perlでできるよ - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/10>

L<Acme: Acme::Yomeru - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/10>

L<English: Use Perl with UNIX tools - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/10>

L<Casual: Data::Validatorでバリデーションする - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/10>

L<Hacker: WebService::Async でウェブサービスの非同期アクセスを簡単に! あるいは私は如何にしてMacBookProを手に入れたか？ - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/10>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

