title: 2010-12-02
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: Setting the bar high with an array of unique gifts|http://perladvent.org/2010/2/>

L<Catalyst: Catalyst Advent Calendar - Day 2|http://www.catalystframework.org/calendar/2010/2>

L<Dancer:  Why routes - route-based programming introduction - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/2>

L<Perl 6: 2010  December  02 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/2/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Bringing out the Good Exporter for Company  |http://advent.rjbs.manxome.org/2010/2010-12-02.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: コマンドラインツールをつくってみよう - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/2>

L<Symbolic Programming: PHPでも記号プログラミング！ - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/2>

L<Meta Advent Calendar: URLに応じたページが表示されるまで - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/2>

L<Win32: Windows GUI アプリケーションでの Perl プラグインの作り方 - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/2>

L<Acme: Acme::Pokemon - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/2>

L<English: To Write Perl For The Perl Beginners. - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/2>

L<Casual: PODのコード部分をかっこよくHTMLでみたいよねー - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/2>

L<Hacker: Jonkで作るおれおれJobQueueフレームワーク - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/2>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

