title: 2010-12-23
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: You'll never find my Christmas|http://perladvent.org/2010/23/>

L<Catalyst: Catalyst Advent Calendar - Day 23|http://www.catalystframework.org/calendar/2010/23>

L<Dancer:  Dancer's ecosystem - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/23>

L<Perl 6: 2010  December  23 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/23/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Rolling Your Own Composition  |http://advent.rjbs.manxome.org/2010/2010-12-23.html>

=head2 Perl Advent Calendar Japan:

L<Perl6:  - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/23>

L<Symbolic Programming: Python SyntaxError Programming を解析してみた - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/23>

L<Meta Advent Calendar:  - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/23>

L<Win32: Encode::EUCJPMSで楽々日本語処理(ただしWindowsに限る) - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/23>

L<Acme: PerlIO::via で遊ぶ - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/23>

L<English: Test::SharedFork - testing with fork(2) - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/23>

L<Casual: 使っちゃいけない標準モジュール - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/23>

L<Hacker: YouTube の動画を保存する - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/23>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

