title: 2010-12-12
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: メリー VAXmas|http://perladvent.org/2010/12/>

L<Catalyst: Catalyst Advent Calendar - Day 12|http://www.catalystframework.org/calendar/2010/12>

L<Dancer:  Adding a feed to your application - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/12>

L<Perl 6: 2010  December  12 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/12/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  One People, One Address Book  |http://advent.rjbs.manxome.org/2010/2010-12-12.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: サブプロセスをforkしたい - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/12>

L<Symbolic Programming: 7種類の記号だけでPerlプログラムを書く - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/12>

L<Meta Advent Calendar: pod に対応する - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/12>

L<Win32: Windows でも Growl を使おう - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/12>

L<Acme: Acme::Ikamusumeで侵略しなイカ？ - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/12>

L<English: Class::Accessor::Lite - yet another accessor builder - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/12>

L<Casual: Image::SizeとImage::Imlib2を使ってCSS Spriteしてみよう - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/12>

L<Hacker: Sub::Argsによる高速簡易バリデーション - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/12>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

