title: 2010-12-14
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: All I want for Christmas is something newer than 5.5.3|http://perladvent.org/2010/14/>

L<Catalyst: Catalyst Advent Calendar - Day 14|http://www.catalystframework.org/calendar/2010/14>

L<Dancer:  Deployment of Dancer applications with Starman, Apache and mod_proxy - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/14>

L<Perl 6: 2010  December  14 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/14/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Wanted: Gift, Got: Gift  |http://advent.rjbs.manxome.org/2010/2010-12-14.html>

=head2 Perl Advent Calendar Japan:

L<Perl6:  - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/14>

L<Symbolic Programming: VB.NETイミディエイトウィンドウで記号プログラミング - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/14>

L<Meta Advent Calendar:  - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/14>

L<Win32: JScriptからperlを呼び出すよ！ - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/14>

L<Acme: Acme::Seclusion::JP - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/14>

L<English: Testing TCP servers with Test::TCP - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/14>

L<Casual: 書き捨てスクリプトを書くときに便利なモジュールとPragmatic Module - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/14>

L<Hacker: DBIx::ObjectMapperでData Mapperパターン! - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/14>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

