title: 2010-12-09
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: Making a list and checking it twice|http://perladvent.org/2010/9/>

L<Catalyst: Catalyst Advent Calendar - Day 9|http://www.catalystframework.org/calendar/2010/9>

L<Dancer:  Writing a Quick NaNoWriMo Graphing Web Application with Dancer - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/9>

L<Perl 6: 2010  December  09 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/9/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  A Place to Shove Your Settings  |http://advent.rjbs.manxome.org/2010/2010-12-09.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: 『Perl6入門』入門 - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/9>

L<Symbolic Programming: サルでもわかるPython顔文字プログラミング - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/9>

L<Meta Advent Calendar: RFC822対応しててサーバアプリケーション動かなくなった - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/9>

L<Win32: 帰る家、HOMEがあるという事実は、幸せにつながる。良いことだよ。 - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/9>

L<Acme: Acme::CheckCharactorsOutsideRange - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/9>

L<English: More Easily To Write Perl By Vim. - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/9>

L<Casual: Google Docsの表計算書類をNet::Google::Spreadsheetsを使ってブラウザ抜きで読み書きする - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/9>

L<Hacker: HTML5 な今だからこその位置情報ハンドリング♡  - Geo::Coordinates::Converter - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/9>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

