title: 2010-12-11
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: karp bo&#x17c;onarodzenie OR Dear Santa, Please REPL|http://perladvent.org/2010/11/>

L<Catalyst: Catalyst Advent Calendar - Day 11|http://www.catalystframework.org/calendar/2010/11>

L<Dancer:  Using DBIx::Class within a Dancer application - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/11>

L<Perl 6: 2010  December  11 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/11/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Putting less on Your Wish List  |http://advent.rjbs.manxome.org/2010/2010-12-11.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: ファイルの扱い - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/11>

L<Symbolic Programming: 記号のみで任意のPowerShellコードを実行 - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/11>

L<Meta Advent Calendar: markdown に対応する - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/11>

L<Win32: Windows で複数の perl を使い分けよう！ - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/11>

L<Acme: CPAN愛のモジュール - Acmeから始まらない物語 - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/11>

L<English: Sub::Throttle - a tiny module for throttling down an operation - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/11>

L<Casual: Perlで文学を嗜む Net::AozoraBunko - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/11>

L<Hacker: Cache::LRU が速い理由 - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/11>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

