title: 2010-12-06
author: len jaffe <lenjaffe@lenjaffe.com>
topic: Perl Advent Planet

=head1 Perl

L<Perl: 2010 Perl Advent Calendar: Spreading Christmas Cheer|http://perladvent.org/2010/6/>

L<Catalyst: Catalyst Advent Calendar - Day 6|http://www.catalystframework.org/calendar/2010/6>

L<Dancer:  Testing a Dancer application - PerlDancer Advent Calendar|http://advent.perldancer.org/2010/6>

L<Perl 6: 2010  December  06 &laquo; Perl 6 Advent Calendar|http://perl6advent.wordpress.com/2010/12/6/>

L<Ricardo Signes:  RJBS Advent Calendar 2010 -  Feast of St. Burl  |http://advent.rjbs.manxome.org/2010/2010-12-06.html>

=head2 Perl Advent Calendar Japan:

L<Perl6: 公開されているモジュールを使ってみよう - JPerl Advent Calendar 2010 Perl6 Track|http://perl-users.jp/articles/advent-calendar/2010/perl6/6>

L<Symbolic Programming: J言語で記号プログラミング - JPerl Advent Calendar 2010 Sym Track|http://perl-users.jp/articles/advent-calendar/2010/sym/6>

L<Meta Advent Calendar: RSS 出力対応した作業ログ - JPerl Advent Calendar 2010 Meta_adcal Track|http://perl-users.jp/articles/advent-calendar/2010/meta_adcal/6>

L<Win32: CPANモジュールをWindowsのみで作成する方法 - JPerl Advent Calendar 2010 Win32 Track|http://perl-users.jp/articles/advent-calendar/2010/win32/6>

L<Acme: Acme::PrettyCure - JPerl Advent Calendar 2010 Acme Track|http://perl-users.jp/articles/advent-calendar/2010/acme/6>

L<English: Useful modules for writing tool scripts (opts, Config::Pit and Script::State) - JPerl Advent Calendar 2010 English Track|http://perl-users.jp/articles/advent-calendar/2010/english/6>

L<Casual: MySQL と SQLite に対応した DBIx なモジュールを PostgreSQL に対応させる Tips いくつか - JPerl Advent Calendar 2010 Casual Track|http://perl-users.jp/articles/advent-calendar/2010/casual/6>

L<Hacker: 変態的正規表現モジュールを支える Regexp::Assemble::Compressed - JPerl Advent Calendar 2010 Hacker Track|http://perl-users.jp/articles/advent-calendar/2010/hacker/6>

teng: is unavailable.

=head1 Entrepreneurship Advent

24 Ways to Start: is unavailable.

=head1 PHP

The PHP advent uses slugged titles for their URIs, so we can't acdcess them by day of month llike everybody else.
You can find the PHP Advent Calendar here
L<PHPadvent: PHP Advent 2010|http://www.phpadvent.org/2010>

=head1 HTML5 Adventure Calendar

HTML5: is unavailable.

=head1 SysAdvent
 
L<SysAdvent: sysadvent|http://sysadvent.blogspot.com>

